config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments

  resources :blog_posts

  root 'home#index'

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
	belongs_to :user
	has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :blog_post
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :blog_posts
has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!

end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

  # GET /blog_posts
  # GET /blog_posts.json
  def index
    @blog_posts = BlogPost.all
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully created.' }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1
  # PATCH/PUT /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: 'Blog post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :author, :blog_entry, :user_id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to blog_post_path(id: @comment.blog_post_id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :comment_entry, :blog_post_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blog_posts/_form.html.erb
<%= form_for(@blog_post) do |f| %>
  <% if @blog_post.errors.any? %>
   <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="form-group">
    <div class="row">
    <%= f.label :title, class: "sr-only" %>
    <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
  </div>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="form-group">
    <%= f.label :blog_entry, class: "sr-only" %>
    <%= f.text_area :blog_entry, class: "form-control", placeholder: "Entry", rows: 10 %>
  </div>
  <div class="form-group cant-see-me">
    <%= f.number_field :user_id, value: current_user.id %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Editing Blog Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_post %> |
<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/index.html.erb
<h1>Driven Food Posts</h1>

<div class="row">
    <% @blog_posts.each do |blog_post| %>
      <div class="col-md-12">
        <h2><%= link_to blog_post.title, blog_post %></h2>
        <h3><%= blog_post.author %></h3>
        <p><%= blog_post.blog_entry[0..250] %>...<%= link_to "Read More", blog_post %></p>
        <p>
        <%= link_to 'New Blog Post', new_blog_post_path %>

        <%= link_to 'Edit', edit_blog_post_path(blog_post) %>
        <%= link_to 'Destroy', blog_post, method: :delete, data: { confirm: 'Are you sure?' } %>
      </p>
      </div>
<br>
<% end %>
     
     

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/show.html.erb
<h1>Current Blog Posts</h1>
<p id="notice"><%= notice %></p>

<p>
  
</p>
<div class="panel-body">
by <strong><%= @blog_post.user.email %></strong> 

<p>on <%= @blog_post.created_at.strftime("%B %d, %Y") %></p>
  <p>
  <%= @blog_post.blog_entry %>
</p>
<p>
<%= link_to 'Edit', edit_blog_post_path(@blog_post) %>

</p>
</div>

<%= link_to 'Back', blog_posts_path %>






<h4>Comments<h4>
    <%@blog_post.comments.each do |comment| %>
    <div class="panel panel-success">
    	<div class="panel-body">
 <p><strong><%= comment.user.email %><strong> said: </p>
    <p><strong><%= comment.user.email %></p><    



    <% end %> 

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="form-group">
    <%= f.label :comment_entry, class: "sr-only" %>
    <%= f.text_area :comment_entry, class: "form-control", placeholder: "Comment", rows: 5 %>
  </div>
  <div class="field cant-see-me">
    <%=f.number_field :blog_post_id, value: @blog_post.id %>
    <%=f.number_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Comment entry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.comment_entry %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Comment entry:</strong>
  <%= @comment.comment_entry %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap 101 Template</title>
  <title>Driven Food</title>


<nav class="navbar navbar-default">
 <div class="container-fluid">
   <!-- Brand and toggle get grouped for better mobile display -->
   <div class="navbar-header">
     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
       <span class="sr-only">Toggle navigation</span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
     </button>
     <a class="navbar-brand" href="#">Brand</a>
   </div>    <!-- Collect the nav links, forms, and other content for toggling -->
   <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     <ul class="nav navbar-nav">
       <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
       <li><a href="#">Link</a></li>
       <li class="dropdown">
         <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
         <ul class="dropdown-menu" role="menu">
           <li><a href="#">Action</a></li>
           <li><a href="#">Another action</a></li>
           <li><a href="#">Something else here</a></li>
           <li class="divider"></li>
           <li><a href="#">Separated link</a></li>
           <li class="divider"></li>
           <li><a href="#">One more separated link</a></li>
         </ul>
       </li>
     </ul>
     <form class="navbar-form navbar-left" role="search">
       <div class="form-group">
         <input type="text" class="form-control" placeholder="Search">
       </div>
       <button type="submit" class="btn btn-default">Submit</button>
     </form>
    
         <ul class="dropdown-menu" role="menu">
           <li><a href="#">Action</a></li>
           <li><a href="#">Another action</a></li>
           <li><a href="#">Something else here</a></li>
           <li class="divider"></li>
           <li><a href="#">Separated link</a></li>
         </ul>
       </li>
     </ul>
   </div><!-- /.navbar-collapse -->
 </div><!-- /.container-fluid -->
</nav>
 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<div class="pull right">
		<% if user_signed_in? %>
		<%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
		<% end %>
<%= yield %>
</div>
<div id="footer">
      Copyright 2015, Anita Wright Productions
    </div>
</body>
</html>